name: Julia
description: Set-up Julia for use in your pipeline.
author: https://github.com/maleadt
requirements: [python3, wget]
configuration:
  properties:
    # Defaults to "*.core"
    core_pattern:
      type: string
    # Defaults to "none", can also be "zstd".
    # Make sure you have `zstd` in your path.
    compressor:
      type: string

    # Defaults to no commands, if you use these make sure you have `file` and `gdb` in your path.
    gdb_commands:
      type: array
    # Same as above, only for `lldb`
    lldb_commands:
      type: array
    # Allows forcing a choice between `gdb` and `lldb`
    # Defaults to `lldb` if available, falling back to `gdb` otherwise.
    debugger:
      type: string
    # Don't let the debugger commands run for longer than this value (in seconds).
    # Defaults to "120".
    debugger_timeout:
      type: number

    # If set to any nonempty string, disables the plugin completely.
    disabled:
      type: string
    # If set to `true`, uses `gdb` to dump the list of loaded libraries, then bundles them
    # together into a `.tar` file.  Default: `false`
    create_bundle:
      type: bool
    # If set to `true`, generates large amounts of debugging output.  Default: `false`
    debug_plugin:
      type: bool
  additionalProperties: false
