name: Julia
description: Set-up Julia for use in your pipeline.
author: https://github.com/maleadt
requirements: [python3, wget]
configuration:
  properties:
    # Defaults to "*.core"
    core_pattern:
      type: string
    # Defaults to "none", can also be "zstd".
    # Make sure you have `zstd` in your path.
    compressor:
      type: string
    # Defaults to no commands, if you use these make sure you have `file` and `gdb` in your path.
    gdb_commands:
      type: array
    # If set to any nonempty string, disables the plugin completely.
    disabled:
      type: string
    # If set to `true`, uses `gdb` to dump the list of loaded libraries, then bundles them
    # together into a `.tar.zst` file, instead of just a `.core.zst` file.
    create_bundle:
      type: bool
  additionalProperties: false
